baseURL = "https://translatabot-website.vercel.app/"
languageCode = "en-us"
title = "Translatabot"
enableRobotsTXT = true
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

[params]
  description = "Official site for Translatabot, the GitHub app that simplifies translations."
  author = "Jannik Bertram"
  tagline = "Streamline your translation workflows with ease."

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "features"
    name = "Features"
    url = "/features/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4
